apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- include "selectorLabels" . | nindent 6 }}
  type: {{ .Values.service.type }}
  publishNotReadyAddresses: true
  sessionAffinity: None
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}